services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: casino_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - DB_NAME=casino_db
      - DB_USER=postgres
      - DB_PASSWORD=password123
      - DB_HOST=db
      - DB_PORT=5432
      - JWT_SECRET=66f9322ebccb108b4b328b5ee02230d91455a5d342c2e283094cb86c2d2f49e0a5f98f78584def10457fd765ccbb29164116bcd596e021625202ccf72b94423f
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  postgres_data:
